# Generated by Django 3.0.1 on 2020-04-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('phenotype_name', models.CharField(max_length=16, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Predict_GP_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_predict_relation', models.DecimalField(decimal_places=6, max_digits=10)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmnmf.Gene')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmnmf.Phenotype')),
            ],
        ),
        migrations.CreateModel(
            name='Known_GP_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gp_known_relation', models.DecimalField(decimal_places=6, max_digits=10)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmnmf.Gene')),
                ('phenotype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmnmf.Phenotype')),
            ],
        ),
    ]
